### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by anglepoised** [monospaced/letterpress#13]
Add standards doc to the wiki on github?

Or use some sort of autodoc and build into the repository itself?

**Comment by monospaced** [comment]
leaning towards the second option, as github wikis are not currently in a git repo.

**Comment by anglepoised** [comment]
Agree with that, the wiki is probably not the way to go. I'm leaning towards using github pages: 
http://pages.github.com/
http://github.com/blog/272-github-pages

That keeps it all nicely git-ified, makes publishing straightforward and means we can probably choose between straight-up html/css, markdown or textile.

What do you think? Might be worth getting input from the others when they arrive, too?

BTW, I'm happy to (nominally) own docs assuming no one else wants to.
