### ISSUE TITLE
Add script examples

### ISSUE THREAD

**Issue by anglepoised** [monospaced/letterpress#15]
Be useful to have functioning examples of included scripts somewhere.

**Comment by monospaced** [comment]


**Comment by anglepoised** [comment]
Yes, I figured that if there are going to be scripts that only exist in letterpress (or baked into production sites) it'd be worth having functioning examples; partly to demonstrate how they work and partly so the base mark-up doesn't need to be reconstructed each time.

Do you agree?

**Comment by monospaced** [comment]
defo

**Comment by anglepoised** [comment]
Good stuff. Suggest we leave this issue open for the time being and when we know what letterpress-specific scripts we want in, we create an issue/task for each one.
