### ISSUE TITLE
Should we include an flv player?

### ISSUE THREAD

**Issue by anglepoised** [monospaced/letterpress#16]
Or is that pushing things too far?

Does it bring licensing/cost worries?

**Comment by monospaced** [comment]
have a look at flowplayer.

**Comment by anglepoised** [comment]
Same comment applies here as with Shadowbox. My vote is leave them out but maintain a list of useful/oft-used third-party solutions.

**Comment by monospaced** [comment]
agree

**Comment by anglepoised** [comment]
Added Flowplayer to scripts wiki page.
