### ISSUE TITLE
Should we include Shadowbox?

### ISSUE THREAD

**Issue by anglepoised** [monospaced/letterpress#17]
Or does that create licensing/cost worries?

**Comment by monospaced** [comment]
I think the license states that only mjijackson can offer shadowbox for download.

**Comment by anglepoised** [comment]
Good point; likely to affect other significant third party tools. It also goes against your thoughts re. keeping things minimal, which I agree with.

I reckon it's worth considering some info (either as part of the README or the documentation) that acts as a running list of third party solutions for common patterns e.g. Shadowbox, Flowplayer etc.

**Comment by monospaced** [comment]
+1!

**Comment by anglepoised** [comment]
I know we said no wiki but just for now I've created a page on your master for us to dump things like this in. Once we have pages running, we can move it thataway...
