### ISSUE TITLE
Add image-list generating index.php

### ISSUE THREAD

**Issue by anglepoised** [monospaced/letterpress#3]
It creates a dependency (obviously need to be deploying to a server with php) but it's a useful tool for smush.it.

Might be worth rewriting so:
- The core functions are in one place - perhaps somewhere under build-assets - and the index.php is just a container (makes it easier to update functionality)
- It reads subdirectories as well as the main directory

It could also be worth creating a sample .htaccess plus index page so this could be done directly through apache indexes.

**Comment by monospaced** [comment]
not required, as smushit no longer relies on img elements in markup
